POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0
REDIS_HOST=judge0-redis
REDIS_PORT=6379
SECRET_KEY_BASE=change-this-local-secret
RAILS_ENV=production
ENABLE_WAIT_RESULT=true
MAX_CPU_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=20
MAX_MEMORY_LIMIT=256000
ALLOW_ENABLE_NETWORK=false
